/**
 * @runa-cmd/completions — Bash completion script generator
 *
 * Generates a self-contained bash completion script from a CLISchema.
 * Uses raw COMP_WORDS/COMP_CWORD — no dependency on bash-completion package.
 */

import type { CLISchema, CommandSchema, OptionSchema } from '@runa-cmd/core';
import { escapeBash } from './escape.js';

/** Replace non-identifier characters with underscores */
function safeName(name: string): string {
	return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

/** Build --long option names for an option, including --no-* for booleans */
function optionFlags(opt: OptionSchema): string[] {
	const flags: string[] = [`--${opt.name}`];
	if (opt.type === 'boolean') {
		flags.push(`--no-${opt.name}`);
	}
	if (opt.alias) {
		for (const a of opt.alias) {
			flags.push(a);
		}
	}
	return flags;
}

/** Build the list of all option flag strings for a command context */
function buildOptWords(options: OptionSchema[], globalOptions: OptionSchema[]): string {
	const all = [...options, ...globalOptions];
	return all.flatMap(optionFlags).join(' ');
}

/** Build prev-matching case entries for enum options */
function buildPrevCases(options: OptionSchema[], globalOptions: OptionSchema[]): string {
	const lines: string[] = [];
	const all = [...options, ...globalOptions];
	for (const opt of all) {
		if (opt.type === 'enum' && opt.enumValues?.length) {
			const triggers: string[] = [`--${opt.name}`];
			if (opt.alias) {
				for (const a of opt.alias) {
					triggers.push(a);
				}
			}
			const pattern = triggers.join('|');
			const values = opt.enumValues.map((v) => escapeBash(v)).join(' ');
			lines.push(`            ${pattern})`);
			lines.push(`                COMPREPLY=($(compgen -W '${values}' -- "$cur"))`);
			lines.push('                return ;;');
		}
	}
	return lines.join('\n');
}

/**
 * Recursively collect all case entries for the command tree.
 * Each command becomes a case pattern based on its path.
 */
function collectCases(
	commands: CommandSchema[],
	globalOptions: OptionSchema[],
	prefix: string,
): string[] {
	const entries: string[] = [];

	for (const cmd of commands) {
		const path = prefix ? `${prefix}_${cmd.name}` : `_${cmd.name}`;
		const optWords = buildOptWords(cmd.options, globalOptions);
		const hasSubcmds = cmd.subcommands && cmd.subcommands.length > 0;
		const subcmdNames = hasSubcmds ? (cmd.subcommands ?? []).map((s) => s.name).join(' ') : '';

		const lines: string[] = [];
		lines.push(`        "${path}")`);

		// prev-matching for enum values in this command's context
		const prevCases = buildPrevCases(cmd.options, globalOptions);
		if (prevCases) {
			lines.push('            case "$prev" in');
			lines.push(prevCases);
			lines.push('            esac');
		}

		if (hasSubcmds) {
			lines.push('            if [[ "$cur" == -* ]]; then');
			lines.push(`                COMPREPLY=($(compgen -W '${optWords}' -- "$cur"))`);
			lines.push('            else');
			lines.push(`                COMPREPLY=($(compgen -W '${subcmdNames}' -- "$cur"))`);
			lines.push('            fi');
		} else {
			lines.push('            if [[ "$cur" == -* ]]; then');
			lines.push(`                COMPREPLY=($(compgen -W '${optWords}' -- "$cur"))`);
			lines.push('            fi');
		}
		lines.push('            ;;');
		entries.push(lines.join('\n'));

		if (hasSubcmds) {
			entries.push(...collectCases(cmd.subcommands ?? [], globalOptions, path));
		}
	}

	return entries;
}

/**
 * Generate a complete bash completion script from a CLISchema.
 *
 * @param schema - Full CLI schema from api.getSchema()
 * @param binName - The CLI binary name
 * @returns Complete bash script as a string
 */
export function generateBashCompletions(schema: CLISchema, binName: string): string {
	const funcName = `_${safeName(binName)}_completions`;
	const { commands, globalOptions } = schema;

	const globalOptWords = globalOptions.flatMap(optionFlags).join(' ');
	const topCmdNames = commands.map((c) => c.name).join(' ');

	// Top-level prev cases for global enum options
	const topPrevCases = buildPrevCases([], globalOptions);

	// Nested command cases
	const cmdCases = collectCases(commands, globalOptions, '');

	// Build the top-level option words (commands' options don't apply here)
	const topOptWords = globalOptWords;

	const lines: string[] = [];
	lines.push('#!/usr/bin/env bash');
	lines.push(`# Bash completions for ${escapeBash(binName)}`);
	lines.push('# Generated by @runa-cmd/completions');
	lines.push('');
	lines.push(`${funcName}() {`);
	// biome-ignore lint/suspicious/noTemplateCurlyInString: these are bash variables, not JS template literals
	lines.push('    local cur="${COMP_WORDS[COMP_CWORD]}"');
	// biome-ignore lint/suspicious/noTemplateCurlyInString: bash variable
	lines.push('    local prev="${COMP_WORDS[COMP_CWORD-1]}"');
	lines.push('');
	lines.push('    # Build command path from COMP_WORDS');
	lines.push('    local cmd_path=""');
	lines.push('    local i=1');
	lines.push('    while [[ $i -lt $COMP_CWORD ]]; do');
	// biome-ignore lint/suspicious/noTemplateCurlyInString: bash variable
	lines.push('        case "${COMP_WORDS[i]}" in');
	lines.push('            -*) ;;');
	// biome-ignore lint/suspicious/noTemplateCurlyInString: bash variable
	lines.push('            *) cmd_path="${cmd_path}_${COMP_WORDS[i]}" ;;');
	lines.push('        esac');
	lines.push('        ((i++))');
	lines.push('    done');
	lines.push('');
	lines.push('    case "$cmd_path" in');
	lines.push('        "")');

	// Top-level prev cases
	if (topPrevCases) {
		lines.push('            case "$prev" in');
		lines.push(topPrevCases);
		lines.push('            esac');
	}

	lines.push('            if [[ "$cur" == -* ]]; then');
	lines.push(`                COMPREPLY=($(compgen -W '${topOptWords}' -- "$cur"))`);
	lines.push('            else');
	lines.push(`                COMPREPLY=($(compgen -W '${topCmdNames}' -- "$cur"))`);
	lines.push('            fi');
	lines.push('            ;;');

	for (const entry of cmdCases) {
		lines.push(entry);
	}

	lines.push('    esac');
	lines.push('}');
	lines.push(`complete -F ${funcName} ${binName}`);

	return lines.join('\n');
}
