/**
 * @runa-cmd/completions — Fish completion script generator
 *
 * Generates fish completions as a flat list of `complete` directives.
 * Uses __fish_use_subcommand and __fish_seen_subcommand_from for context.
 */

import type { CLISchema, CommandSchema, OptionSchema } from '@runa-cmd/core';
import { escapeFish } from './escape.js';

/** Generate complete directives for a single option */
function optionDirectives(binName: string, opt: OptionSchema, condition: string): string[] {
	const lines: string[] = [];
	const desc = opt.description ? ` -d '${escapeFish(opt.description)}'` : '';
	const shortAlias = opt.alias?.find((a) => a.startsWith('-') && !a.startsWith('--'));
	const shortFlag = shortAlias ? ` -s ${shortAlias.replace(/^-/, '')}` : '';
	const condPart = condition ? ` -n '${condition}'` : '';

	if (opt.type === 'boolean') {
		// Boolean flags don't take values — no -r
		lines.push(`complete -c ${binName}${condPart}` + ` -l ${opt.name}${shortFlag}${desc}`);
		// --no-* variant
		lines.push(`complete -c ${binName}${condPart}` + ` -l no-${opt.name}${desc}`);
	} else if (opt.type === 'enum' && opt.enumValues?.length) {
		const vals = opt.enumValues.map((v) => escapeFish(v)).join(' ');
		lines.push(
			`complete -c ${binName}${condPart}` +
				` -l ${opt.name}${shortFlag}${desc}` +
				` -r -a '${vals}'`,
		);
	} else {
		// string, number, array — require argument
		lines.push(`complete -c ${binName}${condPart}` + ` -l ${opt.name}${shortFlag}${desc} -r`);
	}

	return lines;
}

/**
 * Recursively generate complete directives for commands.
 */
function generateCommandDirectives(
	binName: string,
	commands: CommandSchema[],
	globalOptions: OptionSchema[],
	parentCondition: string,
	_parentName: string | null,
): string[] {
	const lines: string[] = [];

	for (const cmd of commands) {
		const desc = cmd.description ? ` -d '${escapeFish(cmd.description)}'` : '';

		// Command itself
		lines.push(
			`complete -c ${binName}` +
				` -n '${parentCondition}'` +
				` -a '${escapeFish(cmd.name)}'${desc}`,
		);

		// Command options
		const cmdCondition = `__fish_seen_subcommand_from ${cmd.name}`;
		for (const opt of cmd.options) {
			lines.push(...optionDirectives(binName, opt, cmdCondition));
		}

		// Subcommands
		if (cmd.subcommands && cmd.subcommands.length > 0) {
			lines.push(
				...generateCommandDirectives(
					binName,
					cmd.subcommands,
					globalOptions,
					cmdCondition,
					cmd.name,
				),
			);
		}
	}

	return lines;
}

/**
 * Generate a complete fish completion script from a CLISchema.
 *
 * @param schema - Full CLI schema from api.getSchema()
 * @param binName - The CLI binary name
 * @returns Complete fish script as a string
 */
export function generateFishCompletions(schema: CLISchema, binName: string): string {
	const { commands, globalOptions } = schema;

	const lines: string[] = [];
	lines.push(`# Fish completions for ${escapeFish(binName)}`);
	lines.push('# Generated by @runa-cmd/completions');
	lines.push('');
	lines.push(`complete -c ${binName} -f`);
	lines.push('');

	// Global options (no condition — available everywhere)
	if (globalOptions.length > 0) {
		lines.push('# Global options');
		for (const opt of globalOptions) {
			lines.push(...optionDirectives(binName, opt, ''));
		}
		lines.push('');
	}

	// Commands
	if (commands.length > 0) {
		lines.push('# Commands');
		lines.push(
			...generateCommandDirectives(binName, commands, globalOptions, '__fish_use_subcommand', null),
		);
	}

	return lines.join('\n');
}
